### ISSUE TITLE
Trying to test semantic parsing model

### ISSUE THREAD

**Issue by hyk1996** [emrahbasaran/SPReID#2]
Hello,
I tried to test semantic parsing model but got a error as below:
>   File "/home/kevinh/git/SPReID/modelx.py", line 57, in __call__
>     x = self.pool(x)

> RuntimeError: Chainer's built-in function class object (AveragePooling2D) which is derived from chainer.FunctionNode has been called as if it were a callable. Use FunctionNode.apply() method instead.
> Furthermore, it's not recommended to use built-in function classes directly; use corresponding function aliases (those with snake_case name, such as F.convolution_nd) instead.

I run the code with chainer v4.2, maybe it caused the error?

In addition, whether the performance of human semantic parsing (show in Table 1 of SPReID paper) is measured with 20-class-segmentation settings, or 6-class settings?

Thanks,
Kevin

**Comment by MahdiKalayeh** [comment]
yes, there are some minor changes in recent versions of Chainer. You should be able to easily adapt it. Table 1 is measured with 20 labels, exactly following LIP settings/protocol.

**Comment by hyk1996** [comment]
Thanks. Replacing `x = self.pool(x)` with `x = self.pool.apply((x,))[0]` will solve the problem. By the way, will the training code of semantic parsing model be released?

**Comment by MahdiKalayeh** [comment]
yes

**Comment by aishawn** [comment]
I have extracted the features .csv. Can you tell me how to evaluate it to get mAP?

**Comment by emrahbasaran** [comment]
Each dataset has its own evaluation script. You should use them to compute mAP and ranking results. In the Readme files of the evaluation scripts or on the web pages of the datasets, you can find the necessary information on how to use the csv files you produce.

**Comment by aishawn** [comment]
Thanks for your advices. I have trained DUKE datasets without the 10d pretrained model. And test with official matlab script, get a bad result mAP 0.012.  I think maybe the reason is that I haven't use the 10d prtrained model. I will try it later. Thanks again!

**Comment by hacker-wei** [comment]
what's python version did you used?did you meet this problem ?
could you tell me?thanks


Traceback (most recent call last):
  File "/home/lvv/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/lvv/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/lvv/anaconda2/lib/python2.7/site-packages/chainer/iterators/multiprocess_iterator.py", line 336, in _run
    alive = self._task()
  File "/home/lvv/anaconda2/lib/python2.7/site-packages/chainer/iterators/multiprocess_iterator.py", line 355, in _task
    data_all = future.get(_response_time)
  File "/home/lvv/anaconda2/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by SwanyWu** [comment]
> Thanks for your advices. I have trained DUKE datasets without the 10d pretrained model. And test with official matlab script, get a bad result mAP 0.012. I think maybe the reason is that I haven't use the 10d prtrained model. I will try it later. Thanks again!

Hello,
could you plz tell me how to use the .csv file to evaluate? I noticed that official matlab code require file with .mat

**Comment by hh23333** [comment]
> yes, there are some minor changes in recent versions of Chainer. You should be able to easily adapt it. Table 1 is measured with 20 labels, exactly following LIP settings/protocol.

Hi,
Nice work!
I'm trying to create some segmentation masks generated by semantic parsing model. How can I get the mask like Fig.2 in your paper? Just upsample the 30x30 mask? 
Thanks

**Comment by wuxifang1994** [comment]
> Thanks for your advices. I have trained DUKE datasets without the 10d pretrained model. And test with official matlab script, get a bad result mAP 0.012. I think maybe the reason is that I haven't use the 10d prtrained model. I will try it later. Thanks again!

hi，I run this code and get the 6144-dim feature, so could you tell me how to deal  with the feature extracted and how to evaluate the results. Thank you for your help and time.

**Comment by ajwl-pmli** [comment]
Hello, Do you know how to compute the rank1 and mAP? could you give me the code which compute the rank1 and mAP, My mail is pku1401210454@163.com, Thank you very much!  @hyk1996 @aishawn

> > Thanks for your advices. I have trained DUKE datasets without the 10d pretrained model. And test with official matlab script, get a bad result mAP 0.012. I think maybe the reason is that I haven't use the 10d prtrained model. I will try it later. Thanks again!
> 
> hi，I run this code and get the 6144-dim feature, so could you tell me how to deal with the feature extracted and how to evaluate the results. Thank you for your help and time.

**Comment by ZamSul** [comment]
Hi @hyk1996 
Can you please explain briefly the method to test this model? Like which commands to run in which folder?
