### ISSUE TITLE
map

### ISSUE THREAD

**Issue by kunfei1** [emrahbasaran/SPReID#4]
hellow
I have trained market datasets with the market and duke  pretrained model. And test with python, but get a bad result mAP 0.16. I think although the pretrained is important, the result is  too bad. did some important points need to attention? 
By the way , I use the imagename's persion id like '-1_c1s1_001376_05.jpg', using '-1'. and misunderstand that the code's 'market_gallery.txt' , it contain like 'market/bounding_box_test/-1_c1s1_000401_03.jpg 0',but i could not understand the meaning of '0', it seems all the .jpg follows '0'.

**Comment by kunfei1** [comment]
i just found make a mistake ,but it also only 80map...

**Comment by hacker-wei** [comment]
Load segmentation weights
Push Model to GPU
Main Begins
Exception in thread prefetch_loop:
Traceback (most recent call last):
  File "/home/lvv/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/lvv/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/lvv/anaconda2/lib/python2.7/site-packages/chainer/iterators/multiprocess_iterator.py", line 336, in _run
    alive = self._task()
  File "/home/lvv/anaconda2/lib/python2.7/site-packages/chainer/iterators/multiprocess_iterator.py", line 355, in _task
    data_all = future.get(_response_time)
  File "/home/lvv/anaconda2/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'shape'
Have you ever come across this problem?thank you very much

**Comment by kunfei1** [comment]
yes，you can see the first issue, Replacing x = self.pool(x) with x = self.pool.apply((x,))[0] will solve the problem

**Comment by hacker-wei** [comment]
thank you .I'll try

**Comment by hacker-wei** [comment]
this code have you ever run over?could you send your runned code to me ?i have try your method, but not solve this problem

**Comment by liiiiiiiiil** [comment]
> hellow
> I have trained market datasets with the market and duke pretrained model. And test with python, but get a bad result mAP 0.16. I think although the pretrained is important, the result is too bad. did some important points need to attention?
> By the way , I use the imagename's persion id like '-1_c1s1_001376_05.jpg', using '-1'. and misunderstand that the code's 'market_gallery.txt' , it contain like 'market/bounding_box_test/-1_c1s1_000401_03.jpg 0',but i could not understand the meaning of '0', it seems all the .jpg follows '0'.



> i just found make a mistake ,but it also only 80map...

Hi, I run this code for 20000 iterations, but the mAP is only 0.4445. I didn't pretrain it on 10 reid datasets. I only train it on Market-1501 for 20000 iterations. How do you train it to get 0.80 mAP?
Thanks!

**Comment by kunfei1** [comment]
> 
> 
> > hellow
> > I have trained market datasets with the market and duke pretrained model. And test with python, but get a bad result mAP 0.16. I think although the pretrained is important, the result is too bad. did some important points need to attention?
> > By the way , I use the imagename's persion id like '-1_c1s1_001376_05.jpg', using '-1'. and misunderstand that the code's 'market_gallery.txt' , it contain like 'market/bounding_box_test/-1_c1s1_000401_03.jpg 0',but i could not understand the meaning of '0', it seems all the .jpg follows '0'.
> 
> > i just found make a mistake ,but it also only 80map...
> 
> Hi, I run this code for 20000 iterations, but the mAP is only 0.4445. I didn't pretrain it on 10 reid datasets. I only train it on Market-1501 for 20000 iterations. How do you train it to get 0.80 mAP?
> Thanks!

I just pretrain it on Market1501+Duke....

**Comment by ajwl-pmli** [comment]
Hello, Do you know how to compute the rank1 and mAP? could you give me the code which compute the rank1 and mAP, My mail is pku1401210454@163.com, Thank you very much! @kunfei1
