### ISSUE TITLE
I'm new  of this chainer,Is problem  my vision of python or any other problem ?I doon't know what should i  do ?could you help me  ?

### ISSUE THREAD

**Issue by hacker-wei** [emrahbasaran/SPReID#6]
Load segmentation weights
Push Model to GPU
Main Begins
Exception in thread prefetch_loop:
Traceback (most recent call last):
  File "/home/lvv/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/lvv/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/lvv/anaconda2/lib/python2.7/site-packages/chainer/iterators/multiprocess_iterator.py", line 336, in _run
    alive = self._task()
  File "/home/lvv/anaconda2/lib/python2.7/site-packages/chainer/iterators/multiprocess_iterator.py", line 355, in _task
    data_all = future.get(_response_time)
  File "/home/lvv/anaconda2/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by niruhan** [comment]
your dataset images are not being loaded. Check the dataset path and debug image_path in get_example in datachef.py

**Comment by ajwl-pmli** [comment]
Hello, Do you know how to compute the rank1 and mAP? could you give me the code which compute the rank1 and mAP, My mail is pku1401210454@163.com, Thank you very much! 

> your dataset images are not being loaded. Check the dataset path and debug image_path in get_example in datachef.py
